snc_redis:
  clients:
    default:
      type: predis
      alias: default
      dsns: []
      options:
        profile: 3.2
        # have to set `profile` explicitly to avoid Exception
        # Attempted to call an undefined method named "getEnvPlaceholders" of class
        #    "Symfony\Component\DependencyInjection\ParameterBag\ParameterBag"
        # in Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationPass
        # caused by \Snc\RedisBundle\DependencyInjection\SncRedisExtension::loadPredisClient
        # when trying to resolve `profile`, see $container->resolveEnvPlaceholders($profile, true)
